### PR TITLE
Setup MountableFileServer

### PR DESCRIPTION
**Pull request by stravid**
I tested the uploads with this command:

~~~bash
curl \
  -F "type=public" \
  -F "file=@/Users/david/Pictures/IMG_0486.JPG" \
  http://localhost:2300/files/
~~~

Is there something else that you need?

### CODE REVIEW

**Comment by stravid** [comment]
@tombu this is now ready for use and review :)

**Comment by tombu** [comment]
In my opinion the frontend code shouldn´t have knowledge about how to locate the files. How do you think about passing the complete file URL to the frontend?

**Comment by stravid** [comment]
Yes, true. Let me change that real quick.

**Comment by stravid** [comment]
@tombu I hope my last commit helps you out, I certainly forgot a few things, thanks for pointing that out.

**Comment by tombu** [comment]
@stravid Cool. Those API changes won´t break anything, I´ll just merge it now. Thanks!

**Pull request merged**
